webapp/__init__.py
import os

from flask import Flask

from webapp.blueprints import home, link, miniblog


def create_app(test_config=None):
    """Flaskアプリケーションを作成"""
    app = Flask(__name__, instance_relative_config=True)

    if test_config is None:
        app.config.from_pyfile("config.py", silent=True)
    else:
        app.config.update(test_config)

    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    @app.route("/hello")
    def hello():
        return "Hello World"

    app.register_blueprint(home.bp)
    app.register_blueprint(link.bp)
    app.register_blueprint(miniblog.bp)

    return app

webapp/blueprints/home.py
import sys
from datetime import datetime

from flask import Blueprint, render_template, request

bp = Blueprint("home", __name__, static_folder="./webapp/templates/home/img")


@bp.route("/")
def home():
    place_holder = {
        "title": "ホーム",
    }
    return render_template("home/index.html", **place_holder)

webapp/blueprints/link.py
from flask import Blueprint, render_template

bp = Blueprint("link", __name__)


@bp.route("/link")
def link():
    place_holder = {"title": "リンクページ"}
    return render_template("link/index.html", **place_holder)

webapp/blueprints/miniblog.py
from datetime import datetime
from flask import Blueprint, render_template

bp = Blueprint("miniblog", __name__)


class PostData:
    def get_data(self) -> list[dict]:
        return [
            {
                "post_header": "雑記",
                "post_title": "おためしポスト2",
                "post_body": "本文はhtmlなり、markdownなりしたいところ",
                "post_datetime": datetime.now().strftime("%Y年%m月%d日 %H:%M:%S") 
            },
            {
                "post_header": "雑記",
                "post_title": "おためしポスト1",
                "post_body": "べた書きでJinja2のレンダリングが効くかを確認してます。日付は datetime.now() で取得中。",
                "post_datetime": datetime.now().strftime("%Y年%m月%d日 %H:%M:%S") 
            },
        ]


@bp.route("/miniblog")
def miniblog():
    place_holder = {
        "title": "リンクページ",
        "posts": PostData().get_data()
    }
    return render_template("miniblog/index.html", **place_holder)

webapp/templates/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{title}} - しま場</title>
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <!-- Google Web Font -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100;300;400;500;700&display=swap"
        rel="stylesheet">
    <style>
        html,
        h1,
        h2,
        h3,
        h4,
        h5,
        a,
        p {
            font-family: 'Noto Sans JP', sans-serif;
        }

        a {
            text-decoration: none;
        }

        a:hover {
            text-decoration: underline;
        }
    </style>
</head>

<body>
    {% include "navbar.html" %}
    <div class="container mt-5">
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</body>

</html>

webapp/templates/home/index.html
{% extends "base.html" %}

{% block body %}
<div class="card border-0 my-4">
    <div class="card-body">
        <div class="text-center">
            <img src="{{ url_for('static', filename='images/icon-2_180x180.webp') }}" class="rounded m-2"
                alt="Generated by DALL-E">
        </div>
        <h2 class="fw-light d-flex justify-content-center my-4">ここについて</h2>
        <p class="d-flex justify-content-center mt-4">色々なことを試すサンドボックス的な場所です。生成AIもよく使います。</p>
        <p class="d-flex justify-content-center">このページはFlaskとJinja2で作っています。</p>
    </div>
</div>
<hr class="mt-4" />
<div class="card border-0 my-4">
    <div class="card-body">
        <h2 class="fw-light d-flex justify-content-center my-4">環境</h2>
        <table class="table table-borderless table-striped">
            <tbody>
                <tr>
                    <th scope="row">言語</th>
                    <td>Python (3.12.4)</td>
                </tr>
                <tr>
                    <th scope="row">フレームワーク</th>
                    <td>Flask</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<hr class="mt-4" />
<div class="card border-0 my-4">
    <div class="card-body">
        <h2 class="fw-light d-flex justify-content-center my-4">About Me</h2>
        <table class="table table-borderless table-striped">
            <tbody>
                <tr>
                    <th scope="row">名前</th>
                    <td>しま (X <a href="https://x.com/klr8550_FB">@klr8550_FB</a>)</td>
                </tr>
                <tr>
                    <th scope="row">仕事の内容</th>
                    <td>通信寄りバックエンドエンジニア</td>
                </tr>
                <tr>
                    <th scope="row">趣味</th>
                    <td>スーパー銭湯めぐり、岩盤浴、ドライブ など</td>
                </tr>
                <tr>
                    <th scope="row">PC</th>
                    <td>Surface Pro（第11世代）</td>
                </tr>
                <tr>
                    <th scope="row">スマホ</th>
                    <td>Pixel 8 Pro</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

webapp/templates/link/index.html
{% extends "base.html" %}

{% block body %}
<h2 class="fw-light d-flex justify-content-center my-4">リンク集</h2>
<div class="alert alert-danger" role="alert">
    このページは未完成です。現在稼働中のリンク集は<a href="https://link.mas2k-dev.net/" class="alert-link">こちら</a>
</div>
<div class="card border-0 my-4">
    <div class="card-body">
        <div class="d-grid gap-2 col-6 mx-auto">
            <a class="btn btn-outline-dark btn-lg m-2" href="{{ url_for('home.home') }}">ホームページ</a>
            <a class="btn btn-outline-dark btn-lg m-2" href="https://github.com/masi2k203">GitHub</a>
            <a class="btn btn-outline-dark btn-lg m-2" href="https://bsky.app/profile/bsky.shima-aki.net">Bluesky</a>
        </div>

    </div>
</div>
{% endblock %}

webapp/templates/miniblog/index.html
{% extends "base.html" %}

{% block body %}
<h2 class="fw-light d-flex justify-content-center my-4">ミニブログ</h2>
<div class="row row-cols-1 row-cols-sm-2 px-2">
    {% for item in posts %}
    {% with item = item %}
    {% include 'miniblog/post_card.html' %}
    {% endwith %}
    {% endfor %}
</div>

{% endblock %}

webapp/templates/miniblog/post_card.html
<div class="card border-light mb-3 shadow-sm">
    <div class="card-header bg-transparent">タグ：{{ item.post_header }}</div>
    <div class="card-body bg-transparent">
        <h5 class="card-title">{{ item.post_title }}</h5>
        <p class="card-text">{{ item.post_body }}</p>
    </div>
    <div class="card-footer bg-transparent text-end text-muted border-0">{{ item.post_datetime }}</div>
</div>

webapp/templates/navbar.html
<nav class="navbar navbar-expand-lg sticky-top bg-body-tertiary opacity-75">
    <div class="container-fluid">
        <a class="navbar-brand fs-3" href="{{ url_for('home.home') }}">しま場</a>
      <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggler">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item p-1">
            <a class="nav-link active" href="{{ url_for('home.home') }}">ホーム</a>
          </li>
          <li class="nav-item p-1">
            <a class="nav-link active" href="{{ url_for('link.link') }}">リンク</a>
          </li>
          <li class="nav-item p-1">
            <a class="nav-link active" href="{{ url_for('miniblog.miniblog') }}">ミニブログ</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>